try {

}
catch (err) {
    console.log(err);
    throw err;
}